language: python

virtualenv:
  system_site_packages: true

before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib

python:
  - "2.7"

env:
  - DJANGO=https://github.com/django/django/archive/master.tar.gz
  - DJANGO=django==1.5 --use-mirrors

install:
  - pip install $DJANGO
  - pip install -r requirements/travis-ci.txt --use-mirrors

script: python manage.py test repository

notifications:
  email: false
