language: python
virtualenv:
  system_site_packages: true
before_install:
 - sudo apt-get install -qq python-numpy python-scipy python-matplotlib mercurial
python:
  - "2.7"
install:
  - pip install -q -r requirements/travis-ci.txt --use-mirrors
  - pip install -q hg+https://code.google.com/p/py-fcm/#egg=fcm
  - cp reflow/settings_tests.py reflow/settings.py
script: python manage_tests.py test repository
notifications:
  email: false
